### ISSUE TITLE
medical images

### ISSUE THREAD

**Issue by whucsu** [CVLAB-Unibo/inr2vec#3]
thanks for sharing.
does this ever tested on medical images, such as ultrasound images ?

**Comment by lykius** [comment]
Hi @whucsu,
Sorry for the late reply.

We never tried to process medical images, that sounds like an interesting path to explore!

**Comment by whucsu** [comment]
there is some INR based medical images reconstruction, such as "A scan-specific unsupervised method for parallel MRI reconstruction via implicit neural representation","NAF---Neural Attenuation Fields for Sparse-View CBCT Reconstruction".

once your team plan to try, I wish we can communicate.
best wishes.
